document: feedback-pipeline-workload
version: 1
data:
  name: thebeanogamer packages
  description: thebeanogamer EPEL packages
  maintainer: thebeanogamer
  packages:
    - reStream
    - remmina
    - remmina-gnome-session
    - remmina-plugins-exec
    - remmina-plugins-python
    - remmina-plugins-rdp
    - remmina-plugins-secret
    - remmina-plugins-vnc
    - remmina-plugins-www
  labels:
    - eln-extras
