document: feedback-pipeline-workload
version: 1
data:
  name: rjones packages
  description: rjones EPEL packages
  maintainer: rjones
  packages: []
  arch_packages:
    aarch64:
      - qemu-sanity-check
    s390x:
      - qemu-sanity-check
    x86_64:
      - qemu-sanity-check
  labels:
    - eln-extras
