document: feedback-pipeline-workload
version: 1
data:
  name: stevetraylen packages
  description: stevetraylen EPEL packages
  maintainer: stevetraylen
  packages:
    - alpine
    - cadaver
    - edg-gridftp-client
    - edg-mkgridmap
    - fetch-crl
    - git2cl
    - tig
    - uberftp
    - xfig
  arch_packages:
    aarch64:
      - diskimage-builder
    s390x:
      - diskimage-builder
    x86_64:
      - diskimage-builder
  labels:
    - eln-extras
