document: feedback-pipeline-workload
version: 1
data:
  name: xavierb packages
  description: xavierb EPEL packages
  maintainer: xavierb
  packages:
    - lemonldap-ng
    - mhonarc
    - openarc
#    - sympa
#    - sympa-httpd
  labels:
    - eln-extras
