document: feedback-pipeline-workload
version: 1
data:
  name: salimma packages
  description: salimma EPEL packages
  maintainer: salimma
  packages:
    - 7zip
    - 7zip-reduced
    - 7zip-standalone
    - 7zip-standalone-all
    - archlinux-keyring
    - autojump
    - fennel
    - fira-code-fonts
    - git-review
    - go-mmproxy
    - khard
    - lagrange
    - linkchecker
    - nickle
    - nvtop
    - plymouth-theme-hot-dog
    - psi-notify
    - squashfuse
    - stow
    - vdirsyncer
    - xbean
    - xdg-terminal-exec
  arch_packages:
    aarch64:
      - zeal
      - zile
    ppc64le:
      - zeal
    s390x:
      - zile
    x86_64:
      - zcfan
      - zeal
      - zile
  labels:
    - eln-extras
