document: feedback-pipeline-workload
version: 1
data:
  name: gursewak packages
  description: gursewak EPEL packages
  maintainer: gursewak
  packages: []
  arch_packages:
    aarch64:
      - bcvk
    x86_64:
      - bcvk
  labels:
    - eln-extras
