document: feedback-pipeline-workload
version: 1
data:
  name: ppisar packages
  description: ppisar EPEL packages
  maintainer: ppisar
  packages:
    - bzip3
    - bzip3-tools
    - cvs
    - gscan2pdf
    - indent
    - shigofumi
    - unpaper
  labels:
    - eln-extras
