document: feedback-pipeline-unwanted
version: 1
data:
  name: Program level unwanted packages
  description: Unwanted packages
  maintainer: bstinson
  unwanted_source_packages:
    - alex
    - beakerlib
    - bind9-next
    - bodhi-client
    - bodhi-messages
    - bodhi-server
    - btrfs-progs
    - cmake-fedora
    - dump
    - erlang
    - etcd
    - python-etcd
    - fedora-packager
    - fedpkg
    - ghc
    - ghc-bytes
    - ghc-bytestring
    - GraphicsMagick
    - happy
    - ImageMagick
    - imake
    - koji
    - libb2
    - metacity
    - mono
    - monodoc
    - nagios-plugins
    - pandoc
    - R
    - R-rpm-macros
    - redhat-lsb
    - reiserfs-utils
    - screen
  labels:
    - eln
    - c10s
