document: feedback-pipeline-unwanted
version: 1
data:
  name: Spice Exclusion List
  description: Spice packages that should not be included.
  maintainer: rhel-sst-virtualization
  unwanted_source_packages:
    - spice
    - spice-gtk
    - spice-html5
    - phodav
    - libgovirt
    - libcacard
    - celt051
    - xorg-x11-drv-qxl
  labels:
    - eln
    - c10s
