document: feedback-pipeline-unwanted
version: 1
data:
  name: Open vSwitch Exclusion List
  description: >
    The OVS packages are shipped through Fast Datapath repositories and should not be included in Red Hat Enterprise Linux.

  maintainer: rhel-sst-network-fastdatapath-ovsdpdk
  unwanted_source_packages:
    - openvswitch
  labels:
    - eln
    - c10s
