document: feedback-pipeline-workload
version: 1
data:
  name: Intel Accelerators Userspace
  description: Userspace libraries and tools for Intel hardware accelerator devices, QAT and IAA.
  maintainer: rhel-sst-kernel-security
  arch_packages:
    x86_64:
      - qatlib
      - qatlib-devel
      - qatlib-service
      - qatlib-tests
      - qatengine
      - qatzip
      - qatzip-devel
      - qatzip-libs
      - qat-zstd-plugin
      - qat-zstd-plugin-devel
      - qat-zstd-plugin-static
      - intel-qpl
      - intel-qpl-devel
  labels:
    - eln
    - c10s
