document: feedback-pipeline-workload
version: 1
data:
  name: radii
  description: Hardware driver manager
  maintainer: rhel-sst-gpu
  package_placeholders:
    - srpm_name: radii
      build_dependencies:
        - go-rpm-macros
      rpms:
        - rpm_name: radii
          description: Hardware driver manager for Linux
          dependencies:
            - glibc
            - radii-hwdata-nv
    - srpm_name: radii-hwdata-nv
      build_dependencies:
        - jq
      rpms:
        - rpm_name: radii-hwdata-nv
          description: Hardware database for NVIDIA GPU chips
  labels:
    - eln
