document: feedback-pipeline-unwanted
version: 1
data:
  name: RDMA Stack - Blocked packages
  description: RDMA Stack - Packages which should not be in ELN
  maintainer: rhel-sst-network-drivers
  unwanted_packages:
    # infiniband-diags provides libibmad library
    - libibmad
    # Intel abandoned next generation OPA hardware development
    - libpsm2
    - opa-fmgui
    # Intel/QLogic QIB/PSM hardware had been disabled since RHEL-8.0
    - infinipath-psm
    # Abandoned upstream packages
    - dapl
    - ibutils
    - qperf
  unwanted_packages:
    # unwanted static library
    - opensm-static
  labels:
    - eln
    - c10s
