document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Packages -- rhel-sst-installer
  description: Packages that should not be distributed in ELN
  maintainer: rhel-sst-installer
  labels:
    - eln
    - c10s
  unwanted_source_packages:
    # Radek Vykydal:
    # system-config-kickstart has been deprecated upstream, it has not
    # been ported to Python 3, and shouldn't have been included in RHEL 8.
    - system-config-kickstart
    # Vendula Poncova: python3-pydbus has been replaced by python3-dasbus
    - python-pydbus
    # Vendula Poncova: python3-nose-testconfig and python3-rpmfluff were
    # pulled in as test dependencies of anaconda, they shouldn't be needed
    - python-nose-testconfig
    - python-rpmfluff
    # Vendula Poncova: python3-ordered-set and python3-ntplib were pulled in
    # as dependencies of anaconda and pykickstart, they shouldn't be needed
    - python-ordered-set
    - python-ntplib
    # Jiri Konecny: dropping InitialSetup from the RHEL-10 to reduce
    # maintenance for the team
    - initial-setup
  unwanted_packages:
    # Jiri Konecny: dropping build-in help content from Anaconda because of
    # Yelp dependency removal
    - anaconda-user-help
