document: feedback-pipeline-unwanted
version: 1
data:
  name: LLVM Toolset Exclusion List
  description: LLVM sub-projects that should not be included.
  maintainer: rhel-sst-pt-llvm-rust-go
  unwanted_packages:
    - libcxx
    - libcxx-devel
    - libcxx-static
    - libcxxabi
    - libcxxabi-devel
    - libcxxabi-static
  unwanted_source_packages:
    - llvm5.0
    - llvm6.0
    - llvm7.0
    - llvm8.0
    - llvm9.0
    - llvm10.0
    - llvm11.0
    - llvm12
    - llvm13
    - llvm14
    - llvm15
    - llvm16
    - llvm17
    - llvm18
    - llvm19
    - llvm20
    - llvm21
    - llvm22
  labels:
    - eln
    - c10s
